version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: ds-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass
      MONGO_INITDB_DATABASE: workshop_mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodata:/data/db
    networks:
      - ds-network

volumes:
  mongodata:

networks:
  ds-network:
 
